### PR TITLE
added both action and script to 'Duplicate a single file/folder'

### PR DESCRIPTION
**Pull request by SjoerdV**
You need to have a $MYSCRIPTS variable loaded in your `.profile`
- the Action (desktop file) will give a context menu called 'Duplicate' on a singularly selected file/folder
- the Script (sh file) will copy the file/folder in-place and add an incremental suffix between `%w` and `%x` (if any) (like '-copy1')

### CODE REVIEW

**Comment by tsujan** [comment]
> You need to have a $MYSCRIPTS variable loaded in your .profile

My two cents: User scripts usually go to `~/bin/`, which is (or should be) added to `PATH`. Then, they can be called by their names.

**Comment by SjoerdV** [comment]
> > You need to have a $MYSCRIPTS variable loaded in your .profile
> 
> 
> 
> My two cents: User scripts usually go to `~/bin/`, which is (or should be) added to `PATH`. Then, they can be called by their names.

Sure, I have my scripts in a folder, as part of a cloned repo. So not in ~/bin.

And I prefer not to give my user scripts the option of being called without the full path. Security thingy...

**Comment by stefonarch** [comment]
Works fine, thanks! 
Explaining  the setup inside the *.desktop file in a comment?

**Comment by SjoerdV** [comment]
Great! Yeah well the comment, just for traceability shall we say?

**Pull request merged**
